//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HMIEntities : DbContext
    {
        public HMIEntities()
            : base("name=HMIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alarms> Alarms { get; set; }
        public virtual DbSet<DataTypes> DataTypes { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<Strings> Strings { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<TranslationMaster> TranslationMaster { get; set; }
        public virtual DbSet<Translations> Translations { get; set; }
        public virtual DbSet<UnitOfMeasures> UnitOfMeasures { get; set; }
    }
}
