//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public int IDType { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Max { get; set; }
        public string Description { get; set; }
        public string UM { get; set; }
        public bool ReadOnly { get; set; }
        public bool Visible { get; set; }
        public Nullable<bool> WriteToPlc { get; set; }
        public string Format { get; set; }
        public Nullable<int> IDCategory { get; set; }
        public string Criteria { get; set; }
        public string DefaultValue { get; set; }
    
        public virtual DataTypes DataTypes { get; set; }
    }
}
