//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Strings
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string IT { get; set; }
        public string EN { get; set; }
        public string local { get; set; }
        public string local2 { get; set; }
    }
}
