//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Variable { get; set; }
        public int Type { get; set; }
        public int Size { get; set; }
    
        public virtual DataTypes DataTypes { get; set; }
    }
}
